name: cd-dev-with-docker-compose

on:
  push: # 아래 브랜치에 Push되면 작동
    branches: [ "develop" ]
  pull_request: # 아래 브랜치에 PullRequest 되면 작동
    branches: [ "develop" ]

# 작업들
jobs:
  # 작업 명(본인이 지으면 됨)
  build:
    environment: develop
    runs-on: ubuntu-latest # 대여해주는 서버
    steps:
      - uses: actions/checkout@v3 # 라이브러리 이용
      - name: Set up JDK 17 # JDK 17버전 사용
        uses: actions/setup-java@v3 # 라이브러리 이용
        with:
          java-version: '17' # 지바 버전에 따라 다르게 설정 필요
          distribution: 'temurin'

      - name: Build with Gradle # 빌드 작업
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      # 멀티 플랫폼 이미지를 빌드하기 위하여 사용되는 하이퍼 바이저(에뮬레이터)
      - name: docker amulator
        uses: docker/setup-qemu-action@v2

      # 멀티 플랫폼 이미지를 빌드하기 위한 Docker CLI 확장 플러그인
      - name: docker buildx
        uses: docker/setup-buildx-action@v2

      # 도커에 로그인
      - name: docker hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 도커 파일을 빌드하고 도커 허브 레파지토리에 푸쉬
      - name: docker build & push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ secrets.DOCKER_TAG }}
          platforms: linux/amd64

      - name: make common env
        run: |
          cd ./deploy
          echo '#!/bin/sh' >> .env
          echo 'DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}' >> .env
          echo 'DOCKER_REPOSITORY=${{ secrets.DOCKER_REPOSITORY }}' >> .env
          echo 'DOCKER_TAG=${{ secrets.DOCKER_TAG }}' >> .env

      - name: make spring env
        run: |
          cd ./deploy
          echo '#!/bin/sh' >> spring.env
          echo 'DATABASE_DEV_MYSQL_CLASSNAME=${{ secrets.DATABASE_DEV_MYSQL_CLASSNAME }}' >> spring.env
          echo 'DATABASE_DEV_MYSQL_PASSWORD=${{ secrets.DATABASE_DEV_MYSQL_PASSWORD }}' >> spring.env
          echo 'DATABASE_DEV_MYSQL_URL=${{ secrets.DATABASE_DEV_MYSQL_URL }}' >> spring.env
          echo 'DATABASE_DEV_MYSQL_USERNAME=${{ secrets.DATABASE_DEV_MYSQL_USERNAME }}' >> spring.env

      - name: send file to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_HOST }}
          port: ${{ secrets.EC2_INSTANCrmE_PORT }}
          username: ${{ secrets.EC2_INSTANCE_USERNAME }}
          key: ${{ secrets.EC2_INSTANCE_PRIVATE_KEY }}
          source: "./deploy" # github action 서버 내부 경로
          target: "~/dev"     # ec2 서버 내부 경로
          strip_components: 1       # 덮어쓰기할 file depth

      - name: deploy EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_HOST }}
          port: ${{ secrets.EC2_INSTANCE_PORT }}
          username: ${{ secrets.EC2_INSTANCE_USERNAME }}
          key: ${{ secrets.EC2_INSTANCE_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ secrets.DOCKER_TAG }}
            cd dev/deploy
            docker-compose -p tickerparis-dev-1 down
            docker-compose -p ticketparis-dev-1 up -d
            docker image prune -f
