name: ci-dev-with-docker

on:
  push: # 아래 브랜치에 Push되면 작동
    branches: [ "develop" ]
  pull_request: # 아래 브랜치에 PullRequest 되면 작동
    branches: [ "develop" ]

permissions:
  contents: read

# 작업들
jobs:
  # 작업 명(본인이 지으면 됨)
  build:
    environment: develop
    runs-on: ubuntu-latest # 대여해주는 서버
    steps:
      - uses: actions/checkout@v3 # 라이브러리 이용
      - name: Set up JDK 17 # JDK 17버전 사용
        uses: actions/setup-java@v3 # 라이브러리 이용
        with:
          java-version: '17' # 지바 버전에 따라 다르게 설정 필요
          distribution: 'temurin'

      - name: Build with Gradle # 빌드 작업
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      # 멀티 플랫폼 이미지를 빌드하기 위하여 사용되는 하이퍼 바이저(에뮬레이터)
      - name: docker amulator
        uses: docker/setup-qemu-action@v2

      # 멀티 플랫폼 이미지를 빌드하기 위한 Docker CLI 확장 플러그인
      - name: docker buildx
        uses: docker/setup-buildx-action@v2

      # 도커에 로그인
      - name: docker hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 도커 파일을 빌드하고 도커 허브 레파지토리에 푸쉬
      - name: docker build & push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}
          platforms: linux/arm64

      - name: EC2 deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_HOST }}
          port: ${{ secrets.EC2_INSTANCE_PORT }}
          username: ${{ secrets.EC2_INSTANCE_USERNAME }}
          key: ${{ secrets.EC2_INSTANCE_PRIVATE_KEY }}
          # 도커 허브에서 이미지 pull로 당겨오기
          # 도커 컨테이너를 백 그라운드에서 실행(-d), 호스트의 8081을 컨테이너의 80과 연결
          # 시스템에서 사용하지 않는 도커 이미지들을 제거(떠있지 않은 참조하고 있지 않은 이미지 삭제)
          script: |
            cd dev
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}
            docker run -d -p 80:8081 ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}
            docker image prune -f
