# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push: # 아래 브랜치에 Push되면 작동
    branches: [ "develop" ]
  pull_request: # 아래 브랜치에 PullRequest 되면 작동
    branches: [ "develop" ]

permissions:
  contents: read

# 작업들
jobs:
  # 작업 명(본인이 지으면 됨)
  build:
    environment: dev
    runs-on: ubuntu-latest # 대여해주는 서버
    steps:
      - uses: actions/checkout@v3 # 라이브러리 이용
      - name: Set up JDK 17 # JDK 17버전 사용
        uses: actions/setup-java@v3 # 라이브러리 이용
        with:
          java-version: '17' # 지바 버전에 따라 다르게 설정 필요
          distribution: 'temurin'

      - name: Build with Gradle # 빌드 작업
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build

      # https://github.com/docker/setup-qemu-action
      - name: docker 애뮬레이터(== VM, 하이퍼바이저) 설정
        uses: docker/setup-qemu-action@v2

      # https://github.com/docker/setup-buildx-action
      - name: docker Buildx 설정 (멀티 플랫폼 빌드)
        uses: docker/setup-buildx-action@v2

      # https://github.com/docker/login-action
      - name: docker hub에 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # https://github.com/docker/build-push-action
      - name: docker 빌드하고 푸시까지
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}
          platforms: linux/arm64
